### ISSUE TITLE
Doesn't appear to work with VirtualBox 3.2.0

### ISSUE THREAD

**Issue by dgc** [toptensoftware/VBoxHeadlessTray#1]
I've been using VBoxHeadlessTray successfully for some time but since the upgrade to VirtualBox 3.2.0 I just get an empty list in the "Select Machine" dialog box.

I tried your build instructions with the VirtualBox 3.2.0 SDK but VBoxHeadlessTray failed to build with:

Error   1   error C2259: 'CComObjectNoRef<Base>' : cannot instantiate abstract class    c:\users\dgc\documents\visual studio 2008\projects\vboxheadlesstray\vboxheadlesstray\vboxmachine.h  247 VBoxHeadlessTray
